{ config, pkgs, lib, ... }:

let
  niriConf = ./niri-conf;
in
{
  # niri config ported verbatim from the fedora dotfiles (kdl files are
  # data; niri has no home-manager module in nixpkgs). config.kdl only
  # contains includes, all settings live in conf/*.kdl.
  home.file.".config/niri/config.kdl".source = "${niriConf}/config.kdl";
  home.file.".config/niri/conf".source = "${niriConf}/conf";

  # Seed the DMS-generated dms/*.kdl includes so the first niri start
  # doesn't fail on missing files. These are regenerated by DMS/matugen at
  # runtime, so they are only created when absent (never overwritten).
  home.activation.niriDmsSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    DMS_DIR="$HOME/.config/niri/dms"
    if [ ! -d "$DMS_DIR" ]; then
      $DRY_RUN_CMD mkdir -p "$DMS_DIR"
    fi
    for f in ${niriConf}/../assets/niri-dms/*.kdl; do
      name="$(basename "$f")"
      if [ ! -f "$DMS_DIR/$name" ]; then
        $DRY_RUN_CMD install -m 644 "$f" "$DMS_DIR/$name"
      fi
    done
  '';
}
